"""Generate jevlite_colab.ipynb from the source files in this directory.

The notebook embeds the repo rather than cloning it, so it is a single file you
upload to Colab with nothing else. Regenerate it after editing any module -
the notebook is a build artifact, not a second copy to maintain by hand.

  python make_notebook.py
"""
import json
import pathlib
import re

SRC = ["typed_schema.py", "td_data.py", "model.py", "metrics.py", "plots.py",
       "smoke_test.py",
       "01_ceiling.py", "02_train.py", "03_calibrate.py", "04_eval.py",
       "05_serve.py", "06_export_onnx.py"]

OUT = "jevlite_colab.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {},
            "source": "\n".join(lines)}


def code(*lines):
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": "\n".join(lines)}


def embed_cell(here):
    """One cell that writes every module to disk, as a dict of raw strings."""
    parts = ["# Writes the repo into the Colab filesystem. Generated by",
             "# make_notebook.py - edit the .py files and regenerate, not this cell.",
             "import pathlib", "", "FILES = {}", ""]
    for name in SRC:
        text = (here / name).read_text(encoding="utf-8")
        if "'''" in text:
            raise SystemExit(f"{name} contains ''' which breaks the r'''...''' "
                             "delimiter used to embed it")
        if text.endswith("\\"):
            raise SystemExit(f"{name} ends with a backslash; a raw string cannot")
        parts += [f"FILES[{name!r}] = r'''", text.rstrip("\n"), "'''", ""]
    parts += [
        "for name, text in FILES.items():",
        "    pathlib.Path(name).write_text(text.lstrip('\\n') + '\\n', encoding='utf-8')",
        "print(f'wrote {len(FILES)} files:', ', '.join(sorted(FILES)))",
    ]
    return code(*parts)


def build(here):
    cells = [
        md("# JevLite on Colab",
           "",
           "Train a typed decision engine that answers arbitrary typed questions",
           "about a state in **one forward pass**, and score it against",
           "[TypeSafe Jev](https://www.mindstudio.ai/blog/jev-system-one-model-launch)",
           "on the public",
           "[`LocalLLaMA/typed-decisions`](https://huggingface.co/datasets/LocalLLaMA/typed-decisions)",
           "test split.",
           "",
           "| | accuracy |",
           "|---|---|",
           "| majority-class baseline | 0.483 (measured) |",
           "| JevLite, 6 epochs | 0.568 (measured - undertrained) |",
           "| single random annotator | 0.659 (measured) |",
           "| TypeSafe Jev 1.13.0 | 0.727 (published) |",
           "| best open result reported | 0.766 |",
           "",
           "The 6-epoch run stopped while validation accuracy was still climbing",
           "steeply, so this notebook now trains for 20 with early stopping. On",
           "calibration and speed that same run already beat Jev: **ECE 0.065 vs",
           "0.144** and **65 ms/case on a T4 vs 239 ms** over Jev's API.",
           "",
           "**No API key is needed anywhere in this notebook.** Total runtime on a",
           "free T4 is roughly 20 minutes.",
           "",
           "Set the runtime first: **Runtime -> Change runtime type -> T4 GPU**."),

        md("## 0. Environment"),
        code("!nvidia-smi -L || echo 'NO GPU - set Runtime > Change runtime type > T4 GPU'"),
        code("%pip install -q 'transformers>=4.48' 'datasets>=2.20' scikit-learn"),
        code("# Two things `!cmd` gets wrong in a notebook: it does NOT stop `Run all`",
             "# when a command fails (the error surfaces cells later as a confusing",
             "# FileNotFoundError), and output routed through a pipe is block-buffered,",
             "# so a long job looks frozen. This streams line by line AND raises.",
             "import os",
             "import subprocess",
             "",
             "def run(cmd):",
             "    print('$', cmd, flush=True)",
             "    env = dict(os.environ, PYTHONUNBUFFERED='1')",
             "    p = subprocess.Popen(cmd, shell=True, env=env, text=True,",
             "                         bufsize=1, stdout=subprocess.PIPE,",
             "                         stderr=subprocess.STDOUT)",
             "    for line in p.stdout:",
             "        print(line, end='', flush=True)",
             "    if p.wait():",
             "        print()",
             "        raise SystemExit(",
             "            f'*** FAILED (exit {p.returncode}): {cmd} -- fix this '",
             "            'before running the cells below, they depend on it.')",
             "    print('ok', flush=True)"),

        md("## 1. Write the repo",
           "",
           "Everything below runs the same scripts you would run locally, so any",
           "result here reproduces off Colab unchanged."),
        embed_cell(here),

        md("## 2. Smoke test",
           "",
           "Checks that every label marker lands where the model expects it, that",
           "grouped softmax normalises per question and stays zero on padding, and",
           "that gold distributions key on exactly the labels we score.",
           "",
           "`--all` runs that last check across **all 1,600 rows**, which is not",
           "paranoia: 10% of this dataset is bare `noul` questions carrying no",
           "`criteria` key at all, and that shape does not appear in the first rows",
           "of the first workflow. A 6-row check passes while training dies 300",
           "rows in. ~2 minutes, no GPU needed - cheaper than finding out later."),
        code("run('python smoke_test.py --all')"),

        md("## 3. What you have to beat",
           "",
           "Free numbers, none of which need a trained model:",
           "",
           "- **single annotator** - how often one random rater agrees with the",
           "  consensus. A reference point, *not* a cap: a model that always picks",
           "  the consensus argmax scores 1.000, and Jev already exceeds this.",
           "- **ambiguous** - share of decisions that are near-ties. This is the",
           "  real limit on headline accuracy; above it you are coin-flipping.",
           "- **majority** - always answer the most common label.",
           "- **frozen** - frozen encoder embeddings + logistic regression. This is",
           "  the baseline that beat Jev by 10 points on Banking77 at 44x the speed.",
           "  If the fine-tune below cannot clear it, ship this instead."),
        code("run('python 01_ceiling.py')"),

        md("## 4. Train",
           "",
           "Trains against the consensus **distribution** (soft cross-entropy +",
           "Brier), not the argmax. Training on the winner is the direct cause of",
           "overconfidence: a model taught that a 55/45 case is `true` learns to say",
           "0.95 and is then wrong 45% of the time while claiming near-certainty.",
           "",
           "20 epochs is ~25 min on a T4, and it stops early once validation",
           "stalls for 6 epochs - the best checkpoint is kept either way, so a",
           "longer budget cannot make the result worse, only the wait longer.",
           "",
           "Do **not** lower `--max-len`: states run 401-997 tokens (p50 588), so",
           "512 would truncate 73% of them. Batches already pad to their own",
           "longest example, so the high cap costs nothing."),
        code("run('python 02_train.py --epochs 20 --bs 4 --accum 4 --max-len 1024')"),

        md("## 5. Calibrate",
           "",
           "One temperature **per primitive type**, fitted on a held-out slice of",
           "train. This targets Jev's weakest measured claim: its miscalibration",
           "runs in opposite directions by type (`choice`/`score` overconfident,",
           "`noul` underconfident), so a single global temperature cannot fix both.",
           "",
           "**Measured result from the first full run: this step did nothing.**",
           "The fitted temperatures came back at [1.09, 1.00, 0.98] and applying",
           "them made ECE slightly worse (0.0653 -> 0.0693). Training against the",
           "soft consensus distribution had already done the calibration work.",
           "",
           "So the step now *selects* rather than assumes: it keeps T=1.0 unless",
           "the fit measurably improves validation ECE. A no-op here is a good",
           "outcome - it means your calibration came free with the loss function.",
           "Seconds, on CPU."),
        code("run('python 03_calibrate.py')"),

        md("## 6. Score against Jev",
           "",
           "The official 400-case test split, 2,000 decisions. Watch three things:",
           "",
           "- **accuracy** vs Jev's 0.727 - but ~16% of this split is near-ties,",
           "  so treat small differences as noise",
           "- **ECE** - the top-1-confidence-vs-correctness one, which is what",
           "  published Jev numbers measure. `ECE-dist` answers a different question",
           "  and the two can disagree sharply, so never quote one alone.",
           "- **confidence -> coverage** - if accuracy climbs steeply with the",
           "  threshold, the confidence is real and you can autoroute the top band."),
        code("run('python 04_eval.py')"),

        md("## 7. The charts",
           "",
           "Every step above dumps its numbers to JSON, and this reads them back.",
           "Five figures, each answering one question:",
           "",
           "1. **Scoreboard** - where you landed against Jev and against the",
           "   baselines that need no training at all.",
           "2. **Training curve** - loss and validation accuracy per epoch, in",
           "   separate panels (two scales never share one axis).",
           "3. **Reliability** - confidence against how often the model was",
           "   actually right, before and after temperature scaling. Below the",
           "   diagonal is overconfident; the gap *is* the ECE.",
           "4. **Coverage** - accuracy on the decisions you keep as you raise the",
           "   confidence threshold. This is the chart that says whether you can",
           "   autoroute the confident band and escalate the rest.",
           "5. **Per type** - accuracy and calibration split by noul/choice/score,",
           "   because Jev's own weakness is type-dependent.",
           "",
           "Figures also land in `plots/` as PNGs you can drop into a write-up."),
        code("run('python plots.py --outdir plots')",
             "",
             "from IPython.display import Image, display",
             "import glob",
             "for f in sorted(glob.glob('plots/*.png')):",
             "    display(Image(filename=f))"),

        md("## 8. Dynamic schema",
           "",
           "The point of the label-embedding head: these questions were never seen",
           "in this combination during training, and no retraining happened. The",
           "schema is data at inference time."),
        code("run('python 05_serve.py --demo')"),

        md("## 8b. Want more accuracy? Go bigger (optional, ~45 min)",
           "",
           "The base encoder is 150M parameters. The other open reproduction of",
           "this architecture used DeBERTa-v3-large (0.4B) and reported 0.854",
           "in-domain, so capacity is the next lever after epochs.",
           "",
           "ModernBERT-large is ~395M and still fits a free T4 at batch 2 with",
           "8-step accumulation (same effective batch of 16). It roughly triples",
           "the epoch time, so this is a coffee-length run, not a quick one.",
           "",
           "It writes to a separate checkpoint, so your base model survives. To",
           "score it, rerun the eval with `--ckpt jevlite-large.pt`.",
           "",
           "**If it OOMs**, drop to `--bs 1 --accum 16` before anything else -",
           "the effective batch stays 16 and only the step count changes."),
        code("# Uncomment to run. Check the charts from the base model first:",
             "# if its validation curve was still climbing, more epochs is the",
             "# cheaper win and you should spend the session on that instead.",
             "",
             "# run('python 02_train.py --encoder answerdotai/ModernBERT-large '",
             "#     '--epochs 20 --bs 2 --accum 8 --max-len 1024 '",
             "#     '--out jevlite-large.pt')",
             "# run('python 03_calibrate.py --ckpt jevlite-large.pt')",
             "# run('python 04_eval.py --ckpt jevlite-large.pt')",
             "# run('python plots.py --outdir plots-large')"),

        md("## 9. Keep the checkpoint",
           "",
           "Colab reclaims sessions with ~90 minutes of idle time and you lose the",
           "filesystem with it. Save `jevlite.pt` somewhere before you close the tab.",
           "",
           "Drive is the zero-setup option; the Hub cell below it is better if you",
           "want the model reachable from anywhere."),
        code("# Optional and non-fatal. The mount needs you to authorise a popup,",
             "# so it cannot run unattended and will raise if you skip it or have",
             "# no Drive. Nothing below depends on this cell succeeding.",
             "import os",
             "import shutil",
             "",
             "try:",
             "    from google.colab import drive",
             "    drive.mount('/content/drive')",
             "    dest = '/content/drive/MyDrive/jevlite'",
             "    os.makedirs(dest, exist_ok=True)",
             "    shutil.copy('jevlite.pt', dest)",
             "    print('saved to', dest)",
             "except Exception as e:",
             "    print(f'Drive save skipped ({type(e).__name__}: {e}).')",
             "    print('Use the download cell or the Hub cell below instead - or',",
             "          'just rerun the notebook later, it is only ~20 minutes.')"),
        code("# Simplest alternative: download the checkpoint straight to your machine.",
             "from google.colab import files",
             "files.download('jevlite.pt')"),
        code("# Optional: push to the Hugging Face Hub instead (needs a free write token)",
             "# from huggingface_hub import notebook_login, HfApi",
             "# notebook_login()",
             "# HfApi().upload_file(path_or_fileobj='jevlite.pt',",
             "#                     path_in_repo='jevlite.pt',",
             "#                     repo_id='YOUR_USERNAME/jevlite', repo_type='model')"),

        md("## 10. Export for local / in-browser inference",
           "",
           "This is the advantage an API structurally cannot match: no network hop,",
           "no key, no per-call cost, and the data never leaves the machine. Jev's",
           "measured p50 from Europe is 239 ms; a 150M encoder at this shape runs",
           "~35 ms p50 on single-thread WASM and less on WebGPU.",
           "",
           "Two things to know before you ship the result:",
           "",
           "- the weights land in a ~596 MB `jevlite.onnx.data` sidecar - serve it",
           "  alongside the graph or you load a model with no weights",
           "- int8 shrinks it to ~151 MB but moves logits materially, so rerun",
           "  step 5 against the quantized model rather than reusing its temperatures",
           "",
           "The parity check in this cell is the one that matters: an export that",
           "silently diverges from PyTorch only shows up as wrong decisions later."),
        code("%pip install -q onnx onnxruntime onnxscript",
             "run('python 06_export_onnx.py --quantize')"),
        code("from google.colab import files",
             "files.download('jevlite.onnx')",
             "files.download('jevlite.onnx.data')"),

        md("## Where to go next",
           "",
           "- **Beat it on your own data.** The independent Banking77 result says a",
           "  small model that has seen your workflow beats a general model that has",
           "  not. Point `td_data.load_split` at your own states and questions.",
           "- **Try a bigger encoder.** `--encoder microsoft/deberta-v3-large`",
           "  (0.4B) if the T4 has room - then check the gain is not confined to the",
           "  ambiguous near-tie decisions, where it would be luck.",
           "- **Do not chase the last accuracy point.** ~16% of this split is",
           "  near-ties. Gains there are luck; gains in the coverage table are real."),
    ]

    return {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": [], "gpuType": "T4", "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }


if __name__ == "__main__":
    here = pathlib.Path(__file__).parent
    nb = build(here)
    for c in nb["cells"]:
        for bad in re.findall(r"run\('(?!python )([^']*)'\)", c["source"]):
            raise SystemExit(f"run() call missing the python prefix: {bad!r}")
    # nbformat wants source as a list of lines, each keeping its newline
    for c in nb["cells"]:
        c["source"] = [l + "\n" for l in c["source"].split("\n")]
        c["source"][-1] = c["source"][-1].rstrip("\n")
    pathlib.Path(here / OUT).write_text(
        json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    n_code = sum(c["cell_type"] == "code" for c in nb["cells"])
    size = (here / OUT).stat().st_size
    print(f"wrote {OUT}: {len(nb['cells'])} cells ({n_code} code), {size/1024:.0f} KB")
